### ISSUE TITLE
How does this compare with the module block proposal?

### ISSUE THREAD

**Issue by phenax** [littledan/proposal-module-fragments#1]
This proposal is too similar to the [module blocks proposal](https://github.com/tc39/proposal-js-module-blocks). How does this compare to that?

**Comment by mischnic** [comment]
Have you seen
- https://github.com/littledan/proposal-module-fragments#relationship-to-js-module-blocks and
- https://github.com/tc39/proposal-js-module-blocks#can-module-blocks-help-with-bundling?

**Comment by phenax** [comment]
Oh got it. Closing this issue.
