### ISSUE TITLE
Semantics wording:

### ISSUE THREAD

**Issue by codehag** [littledan/proposal-module-fragments#2]
In https://github.com/littledan/proposal-module-fragments/blob/main/README.md#semantics

It is written: 

> Like other modules, the host is required to return back the same value of that module when it is imported, or an error.

I think you mean that this is a singleton here? Maybe it would be clearer to say: 

Like other modules, if a module is evaluated multiple times, the host is required to return back the same value of that module when it is imported, or the same error. In other words, all modules are singletons

Can create pr if you agree

**Comment by littledan** [comment]
Hmm, that sentence that I wrote is quite confusing! I don't know what you mean by "evaluated multiple times". I think this is trying to say, "Like other modules, each time the module fragment is imported, the host is required to return the same value of that module. In other words, it's a singleton." PRs welcome.
